import { config } from 'dotenv';
config({ path: '.env.local' });
import { neon } from '@neondatabase/serverless';

const sql = neon(process.env.DATABASE_URL!);

// Known slugs from ATO items table
const EGGS    = 'eggs-chicken-duck-goose-quail-turkey-dried-fresh-frozen-powdered-300';
const OATS    = 'rolled-oats-1602';
const BEEF    = 'beef-joints-steaks-ribs-diced-sliced-minced-ground-supplied-for-human-30';
const LAMB    = 'lamb-joints-chops-racks-diced-sliced-minced-ground-supplied-for-human-441';
const SALMON  = 'salmon-whole-or-fillets-supplied-for-human-consumption-raw-fresh-frozen-smoked-677';
const LENTILS = 'lentils-machine-dressed-and-supplied-as-food-446';
const CHICK   = 'chickpeas-machine-dressed-and-supplied-as-food-189';
const MUSH    = 'mushrooms-dried-fresh-frozen-marinated-stuffed-tinned-520';
const OIL     = 'olive-oil-marketed-for-culinary-purposes-554';
const HONEY   = 'honey-405';
const GARLIC  = 'garlic-373';
const BUTTER  = 'butter-135';
const YOGHURT = 'compound-yoghurt-not-marketed-as-an-ingredient-for-confectionery-219';
const TUNA    = 'tinned-fish-herrings-mackerel-fillets-pilchards-salmon-sardines-tuna-1747';

function ing(name: string, quantity: string, unit: string | null = null, item_slug: string | null = null, gst_status: 'GST-free' | 'taxable' | null = null) {
  return { name, quantity, unit, item_slug, gst_status };
}

const recipes = [
  // ── BREAKFAST ────────────────────────────────────────────────────────────────

  {
    slug: 'scrambled-eggs-on-toast',
    title: 'Scrambled Eggs on Toast',
    description: 'Creamy, soft scrambled eggs cooked low and slow with butter — the ultimate quick Aussie brekkie.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 5,
    cook_time_mins: 8,
    servings: 2,
    image_path: '/images/recipes/scrambled-eggs-on-toast.jpg',
    tags: ['quick', 'vegetarian', 'budget', 'kid-friendly'],
    ingredients: [
      ing('eggs', '4', 'large', EGGS, 'GST-free'),
      ing('butter', '20', 'g', BUTTER, 'GST-free'),
      ing('whole milk', '2', 'tbsp', null, 'GST-free'),
      ing('sourdough bread', '4', 'slices', null, 'GST-free'),
      ing('fresh chives', 'small handful', null, null, 'GST-free'),
      ing('salt and black pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Crack the eggs into a bowl, add the milk, season with salt and pepper, and whisk well.',
      'Melt butter in a non-stick pan over low heat. Add the egg mixture.',
      'Using a spatula, gently fold the eggs every 30 seconds, pulling from the edges. Remove from heat while still slightly underdone — residual heat will finish them.',
      'Toast the sourdough. Pile the eggs on top, scatter with chives, and serve immediately.',
    ],
  },

  {
    slug: 'bircher-muesli-with-berries',
    title: 'Bircher Muesli with Fresh Berries',
    description: 'Overnight oats soaked in apple juice and yoghurt, topped with seasonal berries. Prep it the night before for an effortless morning.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 0,
    servings: 2,
    image_path: '/images/recipes/bircher-muesli-with-berries.jpg',
    tags: ['make-ahead', 'vegetarian', 'no-cook', 'healthy'],
    ingredients: [
      ing('rolled oats', '1', 'cup', OATS, 'GST-free'),
      ing('natural yoghurt', '½', 'cup', YOGHURT, 'GST-free'),
      ing('apple juice', '½', 'cup', null, 'GST-free'),
      ing('honey', '1', 'tbsp', HONEY, 'GST-free'),
      ing('fresh strawberries', 'handful', null, null, 'GST-free'),
      ing('fresh blueberries', 'handful', null, null, 'GST-free'),
      ing('toasted almonds', '2', 'tbsp', null, 'taxable'),
      ing('grated apple', '1', 'medium', null, 'GST-free'),
    ],
    method: [
      'Combine the rolled oats, yoghurt, apple juice, grated apple, and honey in a bowl. Stir well.',
      'Cover and refrigerate overnight (or at least 4 hours).',
      'In the morning, give it a good stir and add a splash of milk if it\'s too thick.',
      'Spoon into bowls and top with fresh berries and toasted almonds.',
    ],
  },

  {
    slug: 'veggie-frittata',
    title: 'Veggie Frittata',
    description: 'A hearty baked egg dish loaded with seasonal vegetables — great hot or cold, and perfect for using up whatever\'s in the fridge.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 25,
    servings: 4,
    image_path: '/images/recipes/veggie-frittata.jpg',
    tags: ['vegetarian', 'gluten-free', 'meal-prep', 'healthy'],
    ingredients: [
      ing('eggs', '6', 'large', EGGS, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('zucchini', '1', 'medium', null, 'GST-free'),
      ing('red capsicum', '1', 'small', null, 'GST-free'),
      ing('baby spinach', '2', 'handfuls', null, 'GST-free'),
      ing('mushrooms', '100', 'g', MUSH, 'GST-free'),
      ing('garlic', '2', 'cloves', GARLIC, 'GST-free'),
      ing('feta cheese', '80', 'g', null, 'GST-free'),
      ing('salt and black pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Preheat oven to 180°C. Heat olive oil in an oven-safe frypan over medium heat.',
      'Sauté garlic, capsicum, zucchini, and mushrooms for 5 minutes until softened. Add spinach and stir until wilted.',
      'Whisk eggs with salt and pepper, then pour over the vegetables. Crumble feta on top.',
      'Cook on the stovetop for 2 minutes until edges start to set, then transfer to the oven.',
      'Bake for 15–18 minutes until puffed and golden. Cool for 5 minutes before slicing.',
    ],
  },

  {
    slug: 'banana-smoothie',
    title: 'Banana Smoothie',
    description: 'A thick, creamy banana smoothie made with yoghurt and honey — ready in 2 minutes and filling enough to power through the morning.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 5,
    cook_time_mins: 0,
    servings: 2,
    image_path: '/images/recipes/banana-smoothie.jpg',
    tags: ['quick', 'vegetarian', 'no-cook', 'kid-friendly', 'budget'],
    ingredients: [
      ing('ripe bananas', '2', 'large', null, 'GST-free'),
      ing('natural yoghurt', '½', 'cup', YOGHURT, 'GST-free'),
      ing('milk', '1', 'cup', null, 'GST-free'),
      ing('honey', '1', 'tbsp', HONEY, 'GST-free'),
      ing('ice cubes', '4–6', null, null, null),
      ing('rolled oats', '¼', 'cup (optional, for extra thickness)', OATS, 'GST-free'),
    ],
    method: [
      'Break the bananas into chunks and add to a blender.',
      'Add yoghurt, milk, honey, ice, and oats (if using).',
      'Blend on high for 60 seconds until smooth and creamy.',
      'Pour into glasses and serve immediately.',
    ],
  },

  {
    slug: 'honey-porridge-with-banana',
    title: 'Honey Porridge with Banana',
    description: 'Warming rolled oats porridge sweetened with Australian honey and topped with sliced banana — the simplest, cheapest breakfast going.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 2,
    cook_time_mins: 8,
    servings: 2,
    image_path: '/images/recipes/honey-porridge-with-banana.jpg',
    tags: ['budget', 'vegetarian', 'kid-friendly', 'quick', 'dairy-free-option'],
    ingredients: [
      ing('rolled oats', '1', 'cup', OATS, 'GST-free'),
      ing('milk or water', '2', 'cups', null, 'GST-free'),
      ing('honey', '2', 'tbsp', HONEY, 'GST-free'),
      ing('ripe banana', '1', 'sliced', null, 'GST-free'),
      ing('pinch of salt', '1', null, null, 'GST-free'),
      ing('ground cinnamon', '½', 'tsp', null, 'GST-free'),
    ],
    method: [
      'Combine oats, milk (or water), and a pinch of salt in a saucepan over medium heat.',
      'Cook, stirring frequently, for 5–7 minutes until thick and creamy.',
      'Stir in the cinnamon. Adjust consistency with a splash more liquid if needed.',
      'Spoon into bowls, drizzle generously with honey, and top with banana slices.',
    ],
  },

  {
    slug: 'smoked-salmon-and-poached-eggs',
    title: 'Smoked Salmon and Poached Eggs',
    description: 'A weekend-worthy plate of silky poached eggs and smoked salmon on toast with a squeeze of lemon — no hollandaise required.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 5,
    cook_time_mins: 10,
    servings: 2,
    image_path: '/images/recipes/smoked-salmon-and-poached-eggs.jpg',
    tags: ['weekend', 'healthy', 'gluten-free-option'],
    ingredients: [
      ing('eggs', '4', 'large', EGGS, 'GST-free'),
      ing('smoked salmon', '150', 'g', SALMON, 'GST-free'),
      ing('sourdough or rye bread', '4', 'slices', null, 'GST-free'),
      ing('baby capers', '1', 'tbsp', null, 'GST-free'),
      ing('fresh dill', 'small handful', null, null, 'GST-free'),
      ing('lemon', '½', 'for squeezing', null, 'GST-free'),
      ing('cream cheese', '2', 'tbsp', null, 'GST-free'),
      ing('white vinegar', '1', 'tbsp', null, 'GST-free'),
    ],
    method: [
      'Bring a deep saucepan of water to a gentle simmer. Add the vinegar.',
      'Crack each egg into a small cup. Create a gentle whirlpool in the water and slide in the eggs one at a time.',
      'Poach for 3 minutes for runny yolks. Remove with a slotted spoon and drain on paper towel.',
      'Toast the bread and spread with cream cheese. Layer on smoked salmon.',
      'Top with a poached egg, capers, dill, and a squeeze of lemon.',
    ],
  },

  {
    slug: 'zucchini-and-corn-fritters',
    title: 'Zucchini and Corn Fritters',
    description: 'Crispy, golden fritters packed with grated zucchini and sweet corn — a Aussie café staple that\'s easy to make at home.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 15,
    cook_time_mins: 15,
    servings: 4,
    image_path: '/images/recipes/zucchini-and-corn-fritters.jpg',
    tags: ['vegetarian', 'kid-friendly', 'weekend'],
    ingredients: [
      ing('zucchini', '2', 'medium, grated', null, 'GST-free'),
      ing('corn kernels', '1', 'cup, fresh or frozen', null, 'GST-free'),
      ing('eggs', '2', 'large', EGGS, 'GST-free'),
      ing('self-raising flour', '½', 'cup', null, 'GST-free'),
      ing('feta cheese', '80', 'g, crumbled', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
      ing('natural yoghurt', 'to serve', null, YOGHURT, 'GST-free'),
    ],
    method: [
      'Grate zucchini and squeeze out excess moisture using a clean tea towel.',
      'Combine zucchini, corn, eggs, flour, and feta in a bowl. Season well.',
      'Heat olive oil in a large frypan over medium heat.',
      'Drop heaped tablespoons of batter into the pan and flatten slightly. Cook for 3–4 minutes per side until golden and cooked through.',
      'Serve with a dollop of yoghurt and a simple green salad.',
    ],
  },

  {
    slug: 'overnight-oats-with-mixed-berries',
    title: 'Overnight Oats with Mixed Berries',
    description: 'Set-and-forget oats that soak overnight in milk and honey, ready to grab from the fridge on busy mornings.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 5,
    cook_time_mins: 0,
    servings: 1,
    image_path: '/images/recipes/overnight-oats-with-mixed-berries.jpg',
    tags: ['make-ahead', 'vegetarian', 'no-cook', 'budget', 'meal-prep'],
    ingredients: [
      ing('rolled oats', '½', 'cup', OATS, 'GST-free'),
      ing('milk', '½', 'cup', null, 'GST-free'),
      ing('natural yoghurt', '2', 'tbsp', YOGHURT, 'GST-free'),
      ing('honey', '1', 'tbsp', HONEY, 'GST-free'),
      ing('chia seeds', '1', 'tsp', null, 'GST-free'),
      ing('mixed fresh or frozen berries', 'generous handful', null, null, 'GST-free'),
    ],
    method: [
      'Combine oats, milk, yoghurt, honey, and chia seeds in a jar or container. Stir well.',
      'Cover and refrigerate overnight.',
      'In the morning, top with berries and add a drizzle of extra honey if desired.',
    ],
  },

  {
    slug: 'avocado-on-sourdough',
    title: 'Avocado on Sourdough',
    description: 'The Australian classic — smashed avo on thick sourdough toast with a squeeze of lemon, chilli flakes, and a perfectly poached egg on top.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 5,
    cook_time_mins: 5,
    servings: 2,
    image_path: '/images/recipes/avocado-on-sourdough.jpg',
    tags: ['vegetarian', 'quick', 'healthy'],
    ingredients: [
      ing('ripe avocados', '2', null, null, 'GST-free'),
      ing('sourdough bread', '4', 'thick slices', null, 'GST-free'),
      ing('eggs', '2', 'large (optional)', EGGS, 'GST-free'),
      ing('lemon', '½', 'juiced', null, 'GST-free'),
      ing('dried chilli flakes', '¼', 'tsp', null, 'GST-free'),
      ing('olive oil', '1', 'tbsp', OIL, 'GST-free'),
      ing('salt and black pepper', 'to taste', null, null, 'GST-free'),
      ing('white vinegar', '1', 'tbsp (for poaching)', null, 'GST-free'),
    ],
    method: [
      'Toast the sourdough until golden and crisp.',
      'Halve and pit the avocados. Scoop flesh into a bowl, add lemon juice, season with salt and pepper, and roughly smash with a fork.',
      'If poaching eggs, bring a saucepan of water to a gentle simmer with the vinegar. Poach eggs for 3 minutes.',
      'Spoon the smashed avocado onto toast, drizzle with olive oil, scatter chilli flakes, and top with a poached egg if using.',
    ],
  },

  {
    slug: 'french-toast-with-fresh-fruit',
    title: 'French Toast with Fresh Fruit',
    description: 'Golden, custardy French toast served with sliced seasonal fruit and a drizzle of honey — a simple weekend treat the whole family will love.',
    meal_type: 'breakfast',
    cuisine: 'australian',
    prep_time_mins: 5,
    cook_time_mins: 10,
    servings: 2,
    image_path: '/images/recipes/french-toast-with-fresh-fruit.jpg',
    tags: ['weekend', 'vegetarian', 'kid-friendly'],
    ingredients: [
      ing('eggs', '2', 'large', EGGS, 'GST-free'),
      ing('milk', '¼', 'cup', null, 'GST-free'),
      ing('thick bread slices', '4', null, null, 'GST-free'),
      ing('butter', '20', 'g', BUTTER, 'GST-free'),
      ing('honey', '2', 'tbsp', HONEY, 'GST-free'),
      ing('seasonal fruit', '1', 'cup (banana, strawberries, mango)', null, 'GST-free'),
      ing('ground cinnamon', '½', 'tsp', null, 'GST-free'),
      ing('natural yoghurt', 'to serve', null, YOGHURT, 'GST-free'),
    ],
    method: [
      'Whisk together eggs, milk, and cinnamon in a shallow dish.',
      'Melt butter in a large non-stick frypan over medium heat.',
      'Dip bread slices into the egg mixture, letting each side soak for 10 seconds.',
      'Cook for 2–3 minutes per side until golden and cooked through.',
      'Serve with fresh fruit, a dollop of yoghurt, and a generous drizzle of honey.',
    ],
  },

  // ── LUNCH ────────────────────────────────────────────────────────────────────

  {
    slug: 'pumpkin-soup',
    title: 'Roasted Pumpkin Soup',
    description: 'Silky, deeply flavoured pumpkin soup made with roasted pumpkin and a swirl of yoghurt. Cheap, warming, and endlessly satisfying.',
    meal_type: 'lunch',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 45,
    servings: 4,
    image_path: '/images/recipes/pumpkin-soup.jpg',
    tags: ['vegetarian', 'gluten-free', 'budget', 'meal-prep'],
    ingredients: [
      ing('butternut pumpkin', '1', 'kg, peeled and cubed', null, 'GST-free'),
      ing('brown onion', '1', 'large', null, 'GST-free'),
      ing('garlic', '4', 'cloves', GARLIC, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('vegetable stock', '750', 'ml', null, 'GST-free'),
      ing('natural yoghurt', '2', 'tbsp, to serve', YOGHURT, 'GST-free'),
      ing('fresh ginger', '1', 'tsp, grated', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Preheat oven to 200°C. Toss pumpkin with half the oil, spread on a baking tray, and roast 25–30 minutes until tender and caramelised at the edges.',
      'In a large pot, heat remaining oil over medium heat. Sauté onion, garlic, and ginger for 5 minutes until soft.',
      'Add roasted pumpkin and stock. Bring to the boil, then reduce and simmer for 10 minutes.',
      'Blend with a stick blender until smooth. Season well.',
      'Serve with a swirl of yoghurt and crusty bread on the side.',
    ],
  },

  {
    slug: 'lentil-and-vegetable-soup',
    title: 'Lentil and Vegetable Soup',
    description: 'A hearty, spiced lentil soup loaded with vegetables — budget-friendly, protein-packed, and even better the next day.',
    meal_type: 'lunch',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 35,
    servings: 4,
    image_path: '/images/recipes/lentil-and-vegetable-soup.jpg',
    tags: ['vegan', 'gluten-free', 'budget', 'meal-prep', 'healthy'],
    ingredients: [
      ing('red lentils', '1', 'cup', LENTILS, 'GST-free'),
      ing('brown onion', '1', 'diced', null, 'GST-free'),
      ing('garlic', '3', 'cloves', GARLIC, 'GST-free'),
      ing('carrot', '2', 'diced', null, 'GST-free'),
      ing('celery', '2', 'stalks, diced', null, 'GST-free'),
      ing('tinned diced tomatoes', '400', 'g', null, 'GST-free'),
      ing('vegetable stock', '1', 'L', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('ground cumin', '1', 'tsp', null, 'GST-free'),
      ing('ground coriander', '1', 'tsp', null, 'GST-free'),
      ing('lemon', '1', 'juiced', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Heat olive oil in a large pot over medium heat. Cook onion, garlic, and carrot for 5 minutes.',
      'Add cumin and coriander, stir for 1 minute until fragrant.',
      'Add lentils, tomatoes, celery, and stock. Bring to the boil.',
      'Reduce heat and simmer for 25 minutes until lentils are completely soft.',
      'Stir in lemon juice and season well. Add more stock if too thick.',
    ],
  },

  {
    slug: 'tuna-rice-salad',
    title: 'Tuna and Rice Salad',
    description: 'A filling, protein-rich salad with canned tuna, fluffy rice, and crunchy vegetables — a lunchbox hero that keeps well for days.',
    meal_type: 'lunch',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 20,
    servings: 4,
    image_path: '/images/recipes/tuna-rice-salad.jpg',
    tags: ['budget', 'meal-prep', 'gluten-free', 'healthy'],
    ingredients: [
      ing('long-grain white rice', '1½', 'cups', null, 'GST-free'),
      ing('canned tuna in springwater', '2 × 185g', 'tins, drained', TUNA, 'GST-free'),
      ing('cucumber', '1', 'diced', null, 'GST-free'),
      ing('cherry tomatoes', '200', 'g, halved', null, 'GST-free'),
      ing('red onion', '½', 'finely diced', null, 'GST-free'),
      ing('olive oil', '3', 'tbsp', OIL, 'GST-free'),
      ing('lemon', '1', 'juiced', null, 'GST-free'),
      ing('fresh parsley', 'handful, chopped', null, null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Cook rice according to packet directions. Rinse under cold water and spread to cool.',
      'Whisk together olive oil, lemon juice, salt, and pepper for the dressing.',
      'Combine cooled rice, tuna, cucumber, cherry tomatoes, red onion, and parsley in a large bowl.',
      'Pour over dressing and toss gently. Adjust seasoning.',
      'Serve immediately or refrigerate — it keeps well for 3 days.',
    ],
  },

  {
    slug: 'prawn-and-mango-salad',
    title: 'Prawn and Mango Salad',
    description: 'Juicy prawns and sweet mango on a bed of fresh greens with a zesty lime dressing — the ultimate Australian summer lunch.',
    meal_type: 'lunch',
    cuisine: 'australian',
    prep_time_mins: 15,
    cook_time_mins: 5,
    servings: 2,
    image_path: '/images/recipes/prawn-and-mango-salad.jpg',
    tags: ['gluten-free', 'healthy', 'summer', 'quick'],
    ingredients: [
      ing('cooked king prawns', '300', 'g, peeled', null, 'GST-free'),
      ing('ripe mango', '1', 'sliced', null, 'GST-free'),
      ing('mixed salad leaves', '4', 'cups', null, 'GST-free'),
      ing('avocado', '1', 'sliced', null, 'GST-free'),
      ing('cucumber', '½', 'sliced', null, 'GST-free'),
      ing('fresh chilli', '½', 'finely sliced', null, 'GST-free'),
      ing('lime', '2', 'juiced', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('fresh mint and coriander', 'handful', null, null, 'GST-free'),
      ing('salt', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Whisk lime juice, olive oil, a pinch of salt, and chilli together for the dressing.',
      'Arrange salad leaves on a large platter.',
      'Top with prawns, mango, avocado, and cucumber.',
      'Drizzle dressing over the salad and scatter with fresh mint and coriander.',
      'Serve immediately.',
    ],
  },

  {
    slug: 'lamb-pita-with-tzatziki',
    title: 'Lamb Pita with Tzatziki',
    description: 'Spiced minced lamb in warm pita bread with cool, garlicky tzatziki, fresh tomato, and lettuce — quick, filling, and delicious.',
    meal_type: 'lunch',
    cuisine: 'mediterranean',
    prep_time_mins: 10,
    cook_time_mins: 15,
    servings: 4,
    image_path: '/images/recipes/lamb-pita-with-tzatziki.jpg',
    tags: ['quick', 'kid-friendly'],
    ingredients: [
      ing('lamb mince', '500', 'g', LAMB, 'GST-free'),
      ing('garlic', '3', 'cloves, minced', GARLIC, 'GST-free'),
      ing('ground cumin', '1', 'tsp', null, 'GST-free'),
      ing('ground coriander', '1', 'tsp', null, 'GST-free'),
      ing('olive oil', '1', 'tbsp', OIL, 'GST-free'),
      ing('pita bread', '4', null, null, 'GST-free'),
      ing('natural yoghurt', '½', 'cup', YOGHURT, 'GST-free'),
      ing('cucumber', '½', 'grated', null, 'GST-free'),
      ing('fresh mint', '2', 'tbsp', null, 'GST-free'),
      ing('tomato', '1', 'sliced', null, 'GST-free'),
      ing('cos lettuce', 'handful', null, null, 'GST-free'),
    ],
    method: [
      'Combine yoghurt, grated cucumber (squeezed dry), garlic (half), and mint for the tzatziki. Season and refrigerate.',
      'Heat olive oil in a frypan over high heat. Add lamb, remaining garlic, cumin, and coriander. Cook, breaking up lumps, for 8–10 minutes until browned.',
      'Warm pita bread in a dry pan or oven.',
      'Fill pita with lamb, tzatziki, tomato slices, and lettuce.',
    ],
  },

  {
    slug: 'smashed-chickpea-and-avocado-toast',
    title: 'Smashed Chickpea and Avocado Toast',
    description: 'A plant-based twist on avo toast — herby smashed chickpeas and avocado on sourdough, full of protein and flavour.',
    meal_type: 'lunch',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 0,
    servings: 2,
    image_path: '/images/recipes/smashed-chickpea-and-avocado-toast.jpg',
    tags: ['vegan', 'quick', 'no-cook', 'healthy', 'budget'],
    ingredients: [
      ing('canned chickpeas', '400', 'g, drained', CHICK, 'GST-free'),
      ing('ripe avocado', '1', null, null, 'GST-free'),
      ing('lemon', '1', 'juiced', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('garlic', '1', 'clove, minced', GARLIC, 'GST-free'),
      ing('fresh parsley', 'handful', null, null, 'GST-free'),
      ing('sourdough bread', '4', 'slices', null, 'GST-free'),
      ing('chilli flakes', '¼', 'tsp', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'In a bowl, roughly mash chickpeas with a fork — keep some texture.',
      'Add avocado and continue mashing. Stir in lemon juice, garlic, parsley, olive oil, and chilli. Season well.',
      'Toast the sourdough until golden.',
      'Pile the chickpea and avocado mixture generously onto toast. Drizzle with a little extra olive oil and serve.',
    ],
  },

  {
    slug: 'chicken-and-salad-wrap',
    title: 'Chicken and Salad Wrap',
    description: 'A simple, fresh wrap with shredded roast chicken, crisp salad, and yoghurt dressing — perfect for on-the-go lunches.',
    meal_type: 'lunch',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 0,
    servings: 2,
    image_path: '/images/recipes/chicken-and-salad-wrap.jpg',
    tags: ['quick', 'no-cook', 'kid-friendly', 'meal-prep'],
    ingredients: [
      ing('cooked chicken breast', '300', 'g, shredded', null, 'GST-free'),
      ing('wholegrain wraps', '4', null, null, 'GST-free'),
      ing('natural yoghurt', '3', 'tbsp', YOGHURT, 'GST-free'),
      ing('baby spinach', '2', 'handfuls', null, 'GST-free'),
      ing('avocado', '1', 'sliced', null, 'GST-free'),
      ing('cucumber', '½', 'sliced', null, 'GST-free'),
      ing('cherry tomatoes', '100', 'g, halved', null, 'GST-free'),
      ing('lemon', '½', 'juiced', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Mix yoghurt with lemon juice and season — this is your dressing.',
      'Lay wraps flat. Spread yoghurt dressing down the centre.',
      'Layer spinach, avocado, cucumber, tomatoes, and chicken.',
      'Fold in the sides and roll tightly. Slice in half and serve.',
    ],
  },

  {
    slug: 'mushroom-and-egg-fried-rice',
    title: 'Mushroom and Egg Fried Rice',
    description: 'A quick, satisfying fried rice with mushrooms, egg, and garlic — a great way to use up leftover cooked rice.',
    meal_type: 'lunch',
    cuisine: 'asian',
    prep_time_mins: 5,
    cook_time_mins: 10,
    servings: 2,
    image_path: '/images/recipes/mushroom-and-egg-fried-rice.jpg',
    tags: ['budget', 'quick', 'vegetarian', 'gluten-free'],
    ingredients: [
      ing('cooked jasmine rice', '2', 'cups (cold, day-old is best)', null, 'GST-free'),
      ing('eggs', '2', 'large', EGGS, 'GST-free'),
      ing('mushrooms', '150', 'g, sliced', MUSH, 'GST-free'),
      ing('garlic', '3', 'cloves, minced', GARLIC, 'GST-free'),
      ing('spring onions', '3', 'sliced', null, 'GST-free'),
      ing('olive oil or sesame oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('soy sauce', '2', 'tbsp', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Heat oil in a wok or large frypan over high heat.',
      'Add garlic and mushrooms, stir-fry for 3 minutes until golden.',
      'Push to the side and scramble the eggs in the pan.',
      'Add cold rice, breaking up any clumps. Stir-fry everything together for 3–4 minutes.',
      'Add soy sauce and spring onions, toss well, and serve.',
    ],
  },

  {
    slug: 'minestrone-soup',
    title: 'Minestrone Soup',
    description: 'A big pot of hearty Italian vegetable soup — loaded with seasonal veg, beans, and pasta. Feeds the whole family for very little.',
    meal_type: 'lunch',
    cuisine: 'italian',
    prep_time_mins: 15,
    cook_time_mins: 35,
    servings: 6,
    image_path: '/images/recipes/minestrone-soup.jpg',
    tags: ['vegan', 'budget', 'meal-prep', 'healthy'],
    ingredients: [
      ing('brown onion', '1', 'diced', null, 'GST-free'),
      ing('garlic', '3', 'cloves', GARLIC, 'GST-free'),
      ing('carrot', '2', 'diced', null, 'GST-free'),
      ing('celery', '2', 'stalks, diced', null, 'GST-free'),
      ing('zucchini', '1', 'diced', null, 'GST-free'),
      ing('tinned diced tomatoes', '400', 'g', null, 'GST-free'),
      ing('tinned cannellini beans', '400', 'g, drained', null, 'GST-free'),
      ing('vegetable stock', '1.5', 'L', null, 'GST-free'),
      ing('small pasta', '100', 'g (e.g. ditalini)', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('fresh basil', 'handful', null, null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Heat olive oil in a large pot. Sauté onion, garlic, carrot, and celery for 5 minutes.',
      'Add zucchini, tomatoes, beans, and stock. Bring to the boil.',
      'Reduce heat and simmer for 20 minutes.',
      'Add pasta and cook for a further 10 minutes until tender.',
      'Season well, stir in fresh basil, and serve with crusty bread.',
    ],
  },

  {
    slug: 'thai-beef-salad',
    title: 'Thai Beef Salad',
    description: 'Seared beef sliced thin over a punchy Thai-style salad with lime, chilli, and fresh herbs — light, bold, and restaurant-quality at home.',
    meal_type: 'lunch',
    cuisine: 'thai',
    prep_time_mins: 15,
    cook_time_mins: 8,
    servings: 2,
    image_path: '/images/recipes/thai-beef-salad.jpg',
    tags: ['gluten-free', 'healthy', 'summer'],
    ingredients: [
      ing('beef rump steak', '300', 'g', BEEF, 'GST-free'),
      ing('mixed salad leaves', '4', 'cups', null, 'GST-free'),
      ing('cucumber', '½', 'sliced', null, 'GST-free'),
      ing('cherry tomatoes', '150', 'g, halved', null, 'GST-free'),
      ing('red onion', '½', 'thinly sliced', null, 'GST-free'),
      ing('fresh chilli', '1', 'sliced', null, 'GST-free'),
      ing('lime', '2', 'juiced', null, 'GST-free'),
      ing('olive oil', '1', 'tbsp', OIL, 'GST-free'),
      ing('fish sauce', '1', 'tbsp', null, 'GST-free'),
      ing('fresh coriander and mint', 'large handful', null, null, 'GST-free'),
      ing('garlic', '1', 'clove, minced', GARLIC, 'GST-free'),
    ],
    method: [
      'Whisk lime juice, fish sauce, garlic, and half the chilli together for the dressing.',
      'Brush steak with olive oil and season. Cook in a hot pan 3–4 minutes per side for medium-rare. Rest 5 minutes, then slice thinly.',
      'Arrange salad leaves, cucumber, tomatoes, and red onion on a platter.',
      'Top with beef, drizzle dressing, scatter herbs and remaining chilli.',
    ],
  },

  // ── DINNER ───────────────────────────────────────────────────────────────────

  {
    slug: 'sunday-roast-lamb',
    title: 'Sunday Roast Lamb with Roasted Vegetables',
    description: 'A proper Aussie Sunday roast — leg of lamb studded with garlic and rosemary, roasted alongside potatoes, pumpkin, and carrots.',
    meal_type: 'dinner',
    cuisine: 'australian',
    prep_time_mins: 15,
    cook_time_mins: 120,
    servings: 6,
    image_path: '/images/recipes/sunday-roast-lamb.jpg',
    tags: ['weekend', 'gluten-free', 'family'],
    ingredients: [
      ing('leg of lamb', '2', 'kg', LAMB, 'GST-free'),
      ing('garlic', '6', 'cloves', GARLIC, 'GST-free'),
      ing('fresh rosemary', '4', 'sprigs', null, 'GST-free'),
      ing('olive oil', '3', 'tbsp', OIL, 'GST-free'),
      ing('potatoes', '600', 'g, quartered', null, 'GST-free'),
      ing('butternut pumpkin', '400', 'g, cubed', null, 'GST-free'),
      ing('carrots', '3', 'halved', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Preheat oven to 200°C. Make small incisions across the lamb and push in slices of garlic and rosemary.',
      'Rub the lamb all over with olive oil, salt, and pepper.',
      'Place in a large roasting pan and roast for 30 minutes. Reduce heat to 180°C.',
      'Add vegetables to the pan, toss in the pan juices, and roast for a further 60–70 minutes until lamb is cooked to your liking.',
      'Rest the lamb for 15 minutes, covered loosely in foil, before carving. Serve with pan-roasted vegetables and gravy.',
    ],
  },

  {
    slug: 'grilled-barramundi-with-broccolini',
    title: 'Grilled Barramundi with Steamed Broccolini',
    description: 'Australia\'s favourite fish, grilled golden with lemon and garlic butter, served with crisp steamed broccolini — clean, quick, and stunning.',
    meal_type: 'dinner',
    cuisine: 'australian',
    prep_time_mins: 5,
    cook_time_mins: 12,
    servings: 2,
    image_path: '/images/recipes/grilled-barramundi-with-broccolini.jpg',
    tags: ['gluten-free', 'healthy', 'quick'],
    ingredients: [
      ing('barramundi fillets', '2 × 180g', null, null, 'GST-free'),
      ing('butter', '30', 'g', BUTTER, 'GST-free'),
      ing('garlic', '2', 'cloves, minced', GARLIC, 'GST-free'),
      ing('lemon', '1', 'zest and juice', null, 'GST-free'),
      ing('olive oil', '1', 'tbsp', OIL, 'GST-free'),
      ing('broccolini', '200', 'g', null, 'GST-free'),
      ing('fresh parsley', 'handful', null, null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Pat barramundi fillets dry and season both sides with salt and pepper.',
      'Heat olive oil in a non-stick pan over medium-high heat. Cook fish skin-side down for 4–5 minutes. Flip and cook a further 2–3 minutes until just cooked through.',
      'In the last minute of cooking, add butter, garlic, and lemon zest to the pan. Baste the fish with the buttery juices.',
      'Meanwhile, steam or blanch broccolini for 3 minutes until just tender.',
      'Serve fish over broccolini, spoon pan butter on top, squeeze over lemon juice, and scatter with parsley.',
    ],
  },

  {
    slug: 'beef-and-vegetable-stir-fry',
    title: 'Beef and Vegetable Stir Fry with Rice',
    description: 'Quick weeknight stir fry with tender beef strips, colourful vegetables, and garlic — on the table in under 25 minutes.',
    meal_type: 'dinner',
    cuisine: 'asian',
    prep_time_mins: 10,
    cook_time_mins: 15,
    servings: 4,
    image_path: '/images/recipes/beef-and-vegetable-stir-fry.jpg',
    tags: ['quick', 'gluten-free', 'family'],
    ingredients: [
      ing('beef rump or sirloin', '500', 'g, sliced thin', BEEF, 'GST-free'),
      ing('garlic', '3', 'cloves, minced', GARLIC, 'GST-free'),
      ing('broccoli', '1', 'head, cut into florets', null, 'GST-free'),
      ing('red capsicum', '1', 'sliced', null, 'GST-free'),
      ing('carrot', '1', 'sliced on the diagonal', null, 'GST-free'),
      ing('mushrooms', '150', 'g, sliced', MUSH, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('oyster sauce', '3', 'tbsp', null, 'GST-free'),
      ing('soy sauce', '2', 'tbsp', null, 'GST-free'),
      ing('jasmine rice', '2', 'cups, to serve', null, 'GST-free'),
    ],
    method: [
      'Cook rice according to packet instructions.',
      'Mix oyster sauce and soy sauce together in a bowl.',
      'Heat oil in a wok over high heat. Stir-fry beef in batches for 2 minutes until just browned. Set aside.',
      'In the same wok, stir-fry garlic for 30 seconds, then add vegetables. Cook for 4–5 minutes until just tender.',
      'Return beef, add sauce, and toss everything together for 1 minute. Serve over rice.',
    ],
  },

  {
    slug: 'slow-cooked-lamb-shanks',
    title: 'Slow-Cooked Lamb Shanks',
    description: 'Fall-off-the-bone lamb shanks braised low and slow in rich tomato and red wine — the ultimate winter comfort dish.',
    meal_type: 'dinner',
    cuisine: 'australian',
    prep_time_mins: 15,
    cook_time_mins: 180,
    servings: 4,
    image_path: '/images/recipes/slow-cooked-lamb-shanks.jpg',
    tags: ['weekend', 'gluten-free', 'family', 'slow-cooker-option'],
    ingredients: [
      ing('lamb shanks', '4', null, LAMB, 'GST-free'),
      ing('brown onion', '2', 'diced', null, 'GST-free'),
      ing('garlic', '6', 'cloves', GARLIC, 'GST-free'),
      ing('carrots', '2', 'diced', null, 'GST-free'),
      ing('tinned diced tomatoes', '800', 'g', null, 'GST-free'),
      ing('beef or lamb stock', '500', 'ml', null, 'GST-free'),
      ing('red wine', '250', 'ml (or extra stock)', null, 'taxable'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('fresh rosemary and thyme', '4', 'sprigs', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Preheat oven to 160°C. Season shanks well with salt and pepper.',
      'Heat oil in a large Dutch oven over high heat. Brown shanks all over, 3–4 minutes per side. Set aside.',
      'In the same pot, sauté onion, garlic, and carrot for 5 minutes. Add wine and reduce by half.',
      'Add tomatoes, stock, and herbs. Return shanks to the pot — liquid should come halfway up the shanks.',
      'Cover and braise in the oven for 2.5–3 hours until the meat is falling off the bone. Serve over creamy mashed potato.',
    ],
  },

  {
    slug: 'chicken-and-vegetable-curry',
    title: 'Chicken and Vegetable Curry',
    description: 'A fragrant, mild-to-medium curry loaded with chicken, potato, and spinach — made from scratch with basic pantry spices.',
    meal_type: 'dinner',
    cuisine: 'indian',
    prep_time_mins: 15,
    cook_time_mins: 35,
    servings: 4,
    image_path: '/images/recipes/chicken-and-vegetable-curry.jpg',
    tags: ['gluten-free', 'family', 'meal-prep', 'healthy'],
    ingredients: [
      ing('chicken thighs', '800', 'g, cut into chunks', null, 'GST-free'),
      ing('brown onion', '2', 'diced', null, 'GST-free'),
      ing('garlic', '4', 'cloves', GARLIC, 'GST-free'),
      ing('fresh ginger', '1', 'tbsp, grated', null, 'GST-free'),
      ing('tinned diced tomatoes', '400', 'g', null, 'GST-free'),
      ing('coconut milk', '400', 'ml', null, 'GST-free'),
      ing('potato', '400', 'g, cubed', null, 'GST-free'),
      ing('baby spinach', '2', 'handfuls', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('curry powder', '2', 'tbsp', null, 'GST-free'),
      ing('garam masala', '1', 'tsp', null, 'GST-free'),
      ing('jasmine rice', 'to serve', null, null, 'GST-free'),
    ],
    method: [
      'Heat oil in a large pot. Sauté onion over medium heat for 5 minutes. Add garlic and ginger, cook 1 minute.',
      'Add curry powder and garam masala, stir for 30 seconds until fragrant.',
      'Add chicken, turning to coat in the spices. Cook for 3–4 minutes.',
      'Add tomatoes, coconut milk, and potato. Bring to the boil, then simmer 20–25 minutes until potato is tender.',
      'Stir in spinach until wilted. Season and serve over steamed rice.',
    ],
  },

  {
    slug: 'beef-bolognese',
    title: 'Beef Bolognese',
    description: 'A rich, slow-simmered bolognese sauce with beef mince, tomatoes, and herbs — simple, crowd-pleasing, and even better on day two.',
    meal_type: 'dinner',
    cuisine: 'italian',
    prep_time_mins: 10,
    cook_time_mins: 60,
    servings: 4,
    image_path: '/images/recipes/beef-bolognese.jpg',
    tags: ['family', 'meal-prep', 'budget', 'kid-friendly'],
    ingredients: [
      ing('beef mince', '600', 'g', BEEF, 'GST-free'),
      ing('brown onion', '1', 'finely diced', null, 'GST-free'),
      ing('garlic', '4', 'cloves, minced', GARLIC, 'GST-free'),
      ing('carrot', '1', 'grated', null, 'GST-free'),
      ing('tinned crushed tomatoes', '800', 'g', null, 'GST-free'),
      ing('tomato paste', '2', 'tbsp', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('dried oregano', '1', 'tsp', null, 'GST-free'),
      ing('bay leaves', '2', null, null, 'GST-free'),
      ing('pasta', '400', 'g (spaghetti or pappardelle)', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Heat olive oil in a large, heavy-based saucepan. Brown mince over high heat, breaking up lumps. Set aside.',
      'In the same pan, sauté onion, garlic, and carrot over medium heat for 5 minutes.',
      'Return mince. Add tomato paste, crushed tomatoes, oregano, and bay leaves.',
      'Reduce heat to low, cover partially, and simmer for 45 minutes, stirring occasionally. Season well.',
      'Cook pasta in well-salted boiling water. Toss with sauce and serve.',
    ],
  },

  {
    slug: 'baked-salmon-with-sweet-potato',
    title: 'Baked Salmon with Sweet Potato Mash',
    description: 'Honey-glazed salmon fillets baked until caramelised, served over sweet potato mash with steamed greens — elegant enough for guests, easy enough for a weeknight.',
    meal_type: 'dinner',
    cuisine: 'australian',
    prep_time_mins: 10,
    cook_time_mins: 25,
    servings: 2,
    image_path: '/images/recipes/baked-salmon-with-sweet-potato.jpg',
    tags: ['gluten-free', 'healthy', 'quick'],
    ingredients: [
      ing('salmon fillets', '2 × 180g', null, SALMON, 'GST-free'),
      ing('honey', '2', 'tbsp', HONEY, 'GST-free'),
      ing('garlic', '1', 'clove, minced', GARLIC, 'GST-free'),
      ing('soy sauce', '1', 'tbsp', null, 'GST-free'),
      ing('sweet potatoes', '400', 'g, peeled and cubed', null, 'GST-free'),
      ing('butter', '20', 'g', BUTTER, 'GST-free'),
      ing('milk', '2', 'tbsp', null, 'GST-free'),
      ing('baby spinach or broccolini', '200', 'g, to serve', null, 'GST-free'),
      ing('lemon', '½', 'to serve', null, 'GST-free'),
    ],
    method: [
      'Preheat oven to 200°C. Boil sweet potato until tender, about 15 minutes, then drain and mash with butter and milk. Season.',
      'Mix honey, soy sauce, and garlic. Place salmon on a lined baking tray and brush generously with the glaze.',
      'Bake for 12–14 minutes until cooked through and caramelised.',
      'Steam or blanch the greens for 2–3 minutes.',
      'Serve salmon over sweet potato mash with greens on the side and a wedge of lemon.',
    ],
  },

  {
    slug: 'beef-and-vegetable-stew',
    title: 'Beef and Vegetable Stew',
    description: 'A thick, warming stew with tender beef and vegetables in a rich gravy — Australian winter comfort food at its finest.',
    meal_type: 'dinner',
    cuisine: 'australian',
    prep_time_mins: 15,
    cook_time_mins: 120,
    servings: 6,
    image_path: '/images/recipes/beef-and-vegetable-stew.jpg',
    tags: ['budget', 'family', 'meal-prep', 'gluten-free'],
    ingredients: [
      ing('beef chuck or stewing beef', '800', 'g, cut into 3cm chunks', BEEF, 'GST-free'),
      ing('brown onion', '2', 'diced', null, 'GST-free'),
      ing('garlic', '4', 'cloves', GARLIC, 'GST-free'),
      ing('carrots', '3', 'cut into chunks', null, 'GST-free'),
      ing('potatoes', '400', 'g, cut into chunks', null, 'GST-free'),
      ing('mushrooms', '200', 'g, halved', MUSH, 'GST-free'),
      ing('beef stock', '750', 'ml', null, 'GST-free'),
      ing('tinned diced tomatoes', '400', 'g', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('fresh thyme', '4', 'sprigs', null, 'GST-free'),
      ing('bay leaves', '2', null, null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Heat oil in a large pot over high heat. Brown beef in batches — don\'t overcrowd the pan. Set aside.',
      'Sauté onion and garlic for 3 minutes. Add carrots and cook a further 2 minutes.',
      'Return beef. Add stock, tomatoes, thyme, and bay leaves. Bring to the boil.',
      'Reduce to a low simmer, cover, and cook for 1 hour.',
      'Add potatoes and mushrooms. Cook uncovered for 30 more minutes until beef is tender and sauce has thickened. Season well. Serve with crusty bread.',
    ],
  },

  {
    slug: 'garlic-prawn-linguine',
    title: 'Garlic Prawn Linguine',
    description: 'Plump prawns tossed with linguine in a buttery garlic and white wine sauce with lemon — ready in 20 minutes and sure to impress.',
    meal_type: 'dinner',
    cuisine: 'italian',
    prep_time_mins: 5,
    cook_time_mins: 15,
    servings: 2,
    image_path: '/images/recipes/garlic-prawn-linguine.jpg',
    tags: ['quick', 'healthy'],
    ingredients: [
      ing('raw king prawns', '300', 'g, peeled and deveined', null, 'GST-free'),
      ing('linguine', '200', 'g', null, 'GST-free'),
      ing('garlic', '4', 'cloves, minced', GARLIC, 'GST-free'),
      ing('butter', '40', 'g', BUTTER, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('white wine or chicken stock', '100', 'ml', null, null),
      ing('lemon', '1', 'zest and juice', null, 'GST-free'),
      ing('fresh parsley', 'large handful', null, null, 'GST-free'),
      ing('chilli flakes', '¼', 'tsp', null, 'GST-free'),
      ing('salt and pepper', 'to taste', null, null, 'GST-free'),
    ],
    method: [
      'Cook linguine in well-salted boiling water until al dente. Reserve ½ cup of pasta water before draining.',
      'Heat olive oil and half the butter in a large pan over medium-high heat. Cook prawns 1–2 minutes per side until pink. Set aside.',
      'In the same pan, cook garlic and chilli flakes for 1 minute. Add wine and let it bubble for 1 minute.',
      'Add drained pasta, prawns, remaining butter, lemon zest, and juice. Toss, adding pasta water as needed.',
      'Scatter with parsley and serve immediately.',
    ],
  },

  {
    slug: 'vegetable-and-lentil-dhal',
    title: 'Vegetable and Lentil Dhal',
    description: 'A golden, aromatic dhal loaded with spinach and spices — one of the most nourishing, budget-friendly dinners you can make.',
    meal_type: 'dinner',
    cuisine: 'indian',
    prep_time_mins: 10,
    cook_time_mins: 30,
    servings: 4,
    image_path: '/images/recipes/vegetable-and-lentil-dhal.jpg',
    tags: ['vegan', 'gluten-free', 'budget', 'meal-prep', 'healthy'],
    ingredients: [
      ing('red lentils', '1.5', 'cups, rinsed', LENTILS, 'GST-free'),
      ing('brown onion', '1', 'finely diced', null, 'GST-free'),
      ing('garlic', '4', 'cloves', GARLIC, 'GST-free'),
      ing('fresh ginger', '1', 'tbsp, grated', null, 'GST-free'),
      ing('tinned diced tomatoes', '400', 'g', null, 'GST-free'),
      ing('coconut milk', '400', 'ml', null, 'GST-free'),
      ing('baby spinach', '3', 'handfuls', null, 'GST-free'),
      ing('olive oil', '2', 'tbsp', OIL, 'GST-free'),
      ing('ground turmeric', '1', 'tsp', null, 'GST-free'),
      ing('ground cumin', '1', 'tsp', null, 'GST-free'),
      ing('garam masala', '1', 'tsp', null, 'GST-free'),
      ing('lemon', '1', 'juiced', null, 'GST-free'),
      ing('steamed rice or naan', 'to serve', null, null, 'GST-free'),
    ],
    method: [
      'Heat oil in a large saucepan over medium heat. Sauté onion for 5 minutes until soft.',
      'Add garlic, ginger, turmeric, cumin, and garam masala. Stir for 1 minute until fragrant.',
      'Add lentils, tomatoes, and coconut milk. Stir to combine.',
      'Bring to the boil, then reduce heat and simmer for 20–25 minutes, stirring often, until lentils are completely soft.',
      'Stir in spinach and lemon juice. Season well. Serve over rice with naan.',
    ],
  },
];

async function main() {
  console.log('Creating recipes table...');
  await sql`
    CREATE TABLE IF NOT EXISTS recipes (
      id            SERIAL PRIMARY KEY,
      slug          TEXT UNIQUE NOT NULL,
      title         TEXT NOT NULL,
      description   TEXT NOT NULL,
      meal_type     TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner')),
      cuisine       TEXT,
      prep_time_mins INTEGER NOT NULL,
      cook_time_mins INTEGER NOT NULL,
      servings      INTEGER NOT NULL,
      image_path    TEXT,
      ingredients   JSONB NOT NULL DEFAULT '[]',
      method        JSONB NOT NULL DEFAULT '[]',
      tags          TEXT[] DEFAULT '{}',
      published     BOOLEAN DEFAULT true,
      created_at    TIMESTAMPTZ DEFAULT NOW(),
      updated_at    TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  console.log(`Seeding ${recipes.length} recipes...`);
  let inserted = 0;
  for (const r of recipes) {
    await sql`
      INSERT INTO recipes (slug, title, description, meal_type, cuisine, prep_time_mins, cook_time_mins, servings, image_path, ingredients, method, tags)
      VALUES (
        ${r.slug}, ${r.title}, ${r.description}, ${r.meal_type}, ${r.cuisine ?? null},
        ${r.prep_time_mins}, ${r.cook_time_mins}, ${r.servings}, ${r.image_path ?? null},
        ${JSON.stringify(r.ingredients)}, ${JSON.stringify(r.method)}, ${r.tags}
      )
      ON CONFLICT (slug) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        meal_type = EXCLUDED.meal_type,
        cuisine = EXCLUDED.cuisine,
        prep_time_mins = EXCLUDED.prep_time_mins,
        cook_time_mins = EXCLUDED.cook_time_mins,
        servings = EXCLUDED.servings,
        image_path = EXCLUDED.image_path,
        ingredients = EXCLUDED.ingredients,
        method = EXCLUDED.method,
        tags = EXCLUDED.tags,
        updated_at = NOW()
    `;
    inserted++;
    process.stdout.write(`\r  ${inserted}/${recipes.length}: ${r.slug}`);
  }

  console.log('\nDone! Recipes seeded successfully.');

  // Print image prompts for generation
  console.log('\n── Image prompts ─────────────────────────────────────────────');
  for (const r of recipes) {
    const prompt = buildImagePrompt(r);
    console.log(`${r.slug}|${prompt}`);
  }
}

function buildImagePrompt(r: typeof recipes[0]) {
  const base = 'Professional food photography, warm natural lighting, Australian home kitchen aesthetic, 45-degree angle, shallow depth of field, styled on a rustic wooden or marble surface';
  const dishMap: Record<string, string> = {
    'scrambled-eggs-on-toast': 'Creamy scrambled eggs piled on thick sourdough toast, sprinkled with fresh chives',
    'bircher-muesli-with-berries': 'Bircher muesli in a ceramic bowl topped with vibrant fresh strawberries and blueberries, drizzled with honey',
    'veggie-frittata': 'Golden baked frittata in a cast iron pan, studded with zucchini, capsicum, mushroom and feta',
    'banana-smoothie': 'Thick creamy banana smoothie in a tall glass with a banana beside it',
    'honey-porridge-with-banana': 'Creamy oat porridge in a bowl with sliced banana and a golden honey drizzle',
    'smoked-salmon-and-poached-eggs': 'Poached eggs on sourdough with smoked salmon, capers and dill',
    'zucchini-and-corn-fritters': 'Stack of golden zucchini and corn fritters on a plate with a dollop of yoghurt and fresh herbs',
    'overnight-oats-with-mixed-berries': 'Overnight oats in a glass jar topped with colourful mixed berries and a honey drizzle',
    'avocado-on-sourdough': 'Thick slices of sourdough topped with smashed avocado, poached egg, chilli flakes and microherbs',
    'french-toast-with-fresh-fruit': 'Golden French toast dusted with icing sugar, served with sliced fresh mango and strawberries',
    'pumpkin-soup': 'Smooth roasted pumpkin soup in a wide bowl with a swirl of yoghurt and toasted pumpkin seeds',
    'lentil-and-vegetable-soup': 'Hearty lentil and vegetable soup in a rustic bowl with crusty bread on the side',
    'tuna-rice-salad': 'Colourful tuna and rice salad with cucumber, cherry tomatoes and fresh parsley in a large bowl',
    'prawn-and-mango-salad': 'Australian prawn and mango salad on a white platter with fresh mint and lime',
    'lamb-pita-with-tzatziki': 'Lamb-filled pita bread with tzatziki, fresh tomato and lettuce, halved on a board',
    'smashed-chickpea-and-avocado-toast': 'Chunky smashed chickpea and avocado on sourdough toast with chilli flakes and lemon',
    'chicken-and-salad-wrap': 'Halved wholegrain wrap revealing shredded chicken, avocado and fresh salad',
    'mushroom-and-egg-fried-rice': 'Steaming wok fried rice with mushrooms, scrambled egg and spring onions',
    'minestrone-soup': 'Vibrant Italian minestrone soup in a deep bowl with vegetables, beans and pasta, with crusty bread',
    'thai-beef-salad': 'Thai beef salad with thinly sliced medium-rare steak over fresh greens, chilli and lime',
    'sunday-roast-lamb': 'Carved leg of lamb surrounded by golden roasted vegetables and herbs on a large serving platter',
    'grilled-barramundi-with-broccolini': 'Golden grilled barramundi fillet on a plate with steamed broccolini and lemon butter sauce',
    'beef-and-vegetable-stir-fry': 'Sizzling beef and vegetable stir fry in a wok, served over steamed jasmine rice',
    'slow-cooked-lamb-shanks': 'Fall-off-the-bone braised lamb shank on creamy mashed potato in a deep bowl, rich red wine sauce',
    'chicken-and-vegetable-curry': 'Creamy golden chicken and vegetable curry in a bowl, served with fluffy basmati rice and fresh coriander',
    'beef-bolognese': 'Spaghetti bolognese with rich meat sauce, fresh basil and parmesan on a pasta plate',
    'baked-salmon-with-sweet-potato': 'Honey-glazed baked salmon fillet on orange sweet potato mash with steamed greens',
    'beef-and-vegetable-stew': 'Rich hearty beef and vegetable stew in a Dutch oven, thick gravy with tender vegetables',
    'garlic-prawn-linguine': 'Garlic butter prawns tossed with linguine, lemon zest and fresh parsley in a pasta bowl',
    'vegetable-and-lentil-dhal': 'Golden turmeric lentil dhal with wilted spinach in a bowl over rice, with naan bread',
  };
  return `${dishMap[r.slug] ?? r.title}. ${base}`;
}

main().catch(console.error);
